apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: ccr.ccs.tencentyun.com/argocd/flask-demo
  newTag: 614ff9ba1132c45ea63095ba912955c705a53caa
